language: go

go:
  - "1.10"
  - tip

env:
  - DEP_VERSION="0.5.0" NODE_VERSION="10"

matrix:
  fast_finish: true

notifications:
  email: false

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - nvm install $NODE_VERSION

install:
  - cd $TRAVIS_BUILD_DIR/server && dep ensure
  - cd $TRAVIS_BUILD_DIR/client && yarn install

script:
  - cd $TRAVIS_BUILD_DIR/server && go vet ./...
  - cd $TRAVIS_BUILD_DIR/server && go test -v -cover -race ./...
  - cd $TRAVIS_BUILD_DIR/client && yarn test:CI
