[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "^1.2.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "^1.4.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "^3.0.0"

[[constraint]]
  name = "github.com/google/uuid"
  revision = "281f560d28af7174109514e936f94c2ab2cb2823"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  revision = "70f0258d44cbaa3b6a2581d82f58da01a38e4de4"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.28.2"
