[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "^1.2.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "^1.4.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "^3.0.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "^1.39.0"
